[app]
name = "exapmle"
key  = "this is your app key"
encrypt_key = "4pSf+zOOucXZrnnNamN/HFcUy55bwCcw1HmCi5U5S9w="

[http]
host = "127.0.0.1"
port = 8020

[datasource]
host = "127.0.0.1"
port = 3306
username = "root"
password = "123456"
database = "test"

[log]
level = "debug"

[log.file]
enable = true
file_path = "logs/app.log"

[trace]
  enable = true